version: 0.2

phases:
  pre_build:
    commands:
      #- echo Build completed on `date`
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic   
         
  build:
    commands:
     # - echo Build started on `date`
      #- mvn package -DskipTests
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      #- docker push 869630519277.dkr.ecr.us-east-2.amazonaws.com/petclinic:latest
      - docker push $REPOSITORY_URI:latest
artifacts:
    files: 
      - taskdef.json
      - appspec.yml
    
